# -*- coding: utf-8 -*-
"""「Taiwan_Weather_Analysis_V5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16PdlWjMieSk4VZwwL9ekis_iE2k81szk
"""

import requests

API_KEY = "CWA-17973F66-40B3-4A81-BE7A-2E61598C73BF"

url = "https://opendata.cwa.gov.tw/api/v1/rest/datastore/O-A0001-001"

params = {
    "Authorization": API_KEY,
    "format": "JSON"
}

response = requests.get(url, params=params, verify=False)

print("連線狀態：", response.status_code)

# 將中央氣象署回傳資料轉成 JSON
data = response.json()

# 取得所有氣象站資料
stations = data["records"]["Station"]

print("取得測站數量：", len(stations))

# 尋找臺北、臺中、高雄測站
target_cities = ["臺北", "臺中", "高雄"]

for city in target_cities:
    print("\n==========", city, "==========")

    for station in stations:
        station_name = station["StationName"]

        if city in station_name:
            print(
                "測站名稱：", station_name,
                "｜測站代碼：", station["StationId"]
            )

# ==========================================
# V5：取得臺北、臺中、高雄即時氣象資料
# ==========================================

target_stations = {
    "臺北": "466920",
    "臺中": "467490",
    "高雄": "467441"
}

city_weather = {}

for station in stations:

    station_id = station["StationId"]

    for city, target_id in target_stations.items():

        if station_id == target_id:

            weather = station["WeatherElement"]

            city_weather[city] = {
                "測站": station["StationName"],
                "溫度": weather["AirTemperature"],
                "濕度": weather["RelativeHumidity"],
                "風速": weather["WindSpeed"],
                "觀測時間": station["ObsTime"]["DateTime"]
            }

# 顯示結果
for city, info in city_weather.items():

    print("==========", city, "==========")
    print("測站：", info["測站"])
    print("溫度：", info["溫度"], "°C")
    print("相對濕度：", info["濕度"], "%")
    print("風速：", info["風速"], "m/s")
    print("觀測時間：", info["觀測時間"])
    print()

# ==========================================
# V5：三城市即時溫度比較圖
# ==========================================

import matplotlib.pyplot as plt

cities = ["Taipei", "Taichung", "Kaohsiung"]

temperatures = [
    float(city_weather["臺北"]["溫度"]),
    float(city_weather["臺中"]["溫度"]),
    float(city_weather["高雄"]["溫度"])
]

plt.figure(figsize=(9, 5))

bars = plt.bar(cities, temperatures)

plt.title("Taiwan City Real-Time Temperature Comparison")
plt.xlabel("City")
plt.ylabel("Temperature (°C)")

# 在柱狀圖上顯示數值
for bar, value in zip(bars, temperatures):
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height() + 0.1,
        f"{value:.1f} °C",
        ha="center"
    )

plt.ylim(0, max(temperatures) + 5)
plt.grid(axis="y", alpha=0.3)

plt.tight_layout()

# 儲存圖片
plt.savefig(
    "city_temperature_comparison.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

# ==========================================
# V5：三城市即時相對濕度比較圖
# ==========================================

import matplotlib.pyplot as plt

cities = ["Taipei", "Taichung", "Kaohsiung"]

humidity = [
    float(city_weather["臺北"]["濕度"]),
    float(city_weather["臺中"]["濕度"]),
    float(city_weather["高雄"]["濕度"])
]

plt.figure(figsize=(9, 5))

bars = plt.bar(cities, humidity)

plt.title("Taiwan City Real-Time Humidity Comparison")
plt.xlabel("City")
plt.ylabel("Relative Humidity (%)")

# 在柱子上顯示濕度
for bar, value in zip(bars, humidity):
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height() + 1,
        f"{value:.0f} %",
        ha="center"
    )

plt.ylim(0, 100)
plt.grid(axis="y", alpha=0.3)

plt.tight_layout()

# 儲存圖片
plt.savefig(
    "city_humidity_comparison.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

# ==========================================
# V5：三城市即時風速比較圖
# ==========================================

import matplotlib.pyplot as plt

cities = ["Taipei", "Taichung", "Kaohsiung"]

wind_speed = [
    float(city_weather["臺北"]["風速"]),
    float(city_weather["臺中"]["風速"]),
    float(city_weather["高雄"]["風速"])
]

plt.figure(figsize=(9, 5))

bars = plt.bar(cities, wind_speed)

plt.title("Taiwan City Real-Time Wind Speed Comparison")
plt.xlabel("City")
plt.ylabel("Wind Speed (m/s)")

# 在柱子上顯示風速
for bar, value in zip(bars, wind_speed):
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height() + 0.05,
        f"{value:.1f} m/s",
        ha="center"
    )

plt.grid(axis="y", alpha=0.3)

plt.tight_layout()

# 儲存圖片
plt.savefig(
    "city_wind_speed_comparison.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

# ==========================================
# V5：Taiwan Real-Time Weather Dashboard
# ==========================================

import matplotlib.pyplot as plt
import numpy as np

cities = ["Taipei", "Taichung", "Kaohsiung"]

temperature = [
    float(city_weather["臺北"]["溫度"]),
    float(city_weather["臺中"]["溫度"]),
    float(city_weather["高雄"]["溫度"])
]

humidity = [
    float(city_weather["臺北"]["濕度"]),
    float(city_weather["臺中"]["濕度"]),
    float(city_weather["高雄"]["濕度"])
]

wind_speed = [
    float(city_weather["臺北"]["風速"]),
    float(city_weather["臺中"]["風速"]),
    float(city_weather["高雄"]["風速"])
]

# 建立位置
x = np.arange(len(cities))
width = 0.25

plt.figure(figsize=(11, 6))

# 三組長條
bars1 = plt.bar(x - width, temperature, width, label="Temperature (°C)")
bars2 = plt.bar(x, humidity, width, label="Humidity (%)")
bars3 = plt.bar(x + width, wind_speed, width, label="Wind Speed (m/s)")

# 標題
plt.title(
    "Taiwan Real-Time Weather Dashboard",
    fontsize=18,
    fontweight="bold"
)

plt.xlabel("City")
plt.ylabel("Observed Value")

plt.xticks(x, cities)

plt.legend()

plt.grid(
    axis="y",
    alpha=0.3
)

# 顯示數值
for bar, value in zip(bars1, temperature):
    plt.text(
        bar.get_x() + bar.get_width()/2,
        bar.get_height() + 1,
        f"{value:.1f}°C",
        ha="center"
    )

for bar, value in zip(bars2, humidity):
    plt.text(
        bar.get_x() + bar.get_width()/2,
        bar.get_height() + 1,
        f"{value:.0f}%",
        ha="center"
    )

for bar, value in zip(bars3, wind_speed):
    plt.text(
        bar.get_x() + bar.get_width()/2,
        bar.get_height() + 1,
        f"{value:.1f}",
        ha="center"
    )

plt.tight_layout()

# 儲存 Dashboard
plt.savefig(
    "taiwan_weather_dashboard.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

# V4.3：取得臺北測站即時氣象資料

taipei_station = None

# 找出臺北測站
for station in stations:
    if station["StationName"] == "臺北":
        taipei_station = station
        break

# 顯示臺北測站資料
if taipei_station:
    print("=== 臺北測站即時氣象資料 ===")
    print("測站名稱：", taipei_station["StationName"])
    print("測站代碼：", taipei_station["StationId"])
    print("觀測時間：", taipei_station["ObsTime"]["DateTime"])

    weather = taipei_station["WeatherElement"]

    print("溫度：", weather["AirTemperature"], "°C")
    print("相對濕度：", weather["RelativeHumidity"], "%")
    print("風速：", weather["WindSpeed"], "m/s")
else:
    print("找不到臺北測站")

# V4.4：臺北即時氣象資料視覺化

import matplotlib.pyplot as plt

# 將中央氣象署 API 回傳的文字轉成數值
temperature = float(weather["AirTemperature"])
humidity = float(weather["RelativeHumidity"])
wind_speed = float(weather["WindSpeed"])

print("=== 臺北即時氣象資料 ===")
print("溫度：", temperature, "°C")
print("相對濕度：", humidity, "%")
print("風速：", wind_speed, "m/s")

# 建立圖表資料
items = [
    "Temperature (°C)",
    "Humidity (%)",
    "Wind Speed (m/s)"
]

values = [
    temperature,
    humidity,
    wind_speed
]

# 建立長條圖
plt.figure(figsize=(9, 5))

bars = plt.bar(items, values)

plt.title("Taipei Real-Time Weather Observation")
plt.ylabel("Observed Value")

# 在每個柱子上方顯示實際數值
for bar, value in zip(bars, values):
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height() + 1,
        f"{value:g}",
        ha="center"
    )

plt.tight_layout()

# 儲存圖片
plt.savefig(
    "taipei_realtime_weather.png",
    dpi=150,
    bbox_inches="tight"
)

plt.show()

# V4.5：臺北即時天氣資訊卡

import matplotlib.pyplot as plt

# 使用 V4.3 已取得的真實氣象資料
temperature = float(weather["AirTemperature"])
humidity = float(weather["RelativeHumidity"])
wind_speed = float(weather["WindSpeed"])

# 取得觀測時間
observation_time = taipei_station["ObsTime"]["DateTime"]

# 建立資訊卡
fig = plt.figure(figsize=(9, 7))

# 關閉座標軸
plt.axis("off")

# 標題
plt.text(
    0.5, 0.92,
    "Taipei Real-Time Weather",
    ha="center",
    fontsize=22,
    fontweight="bold"
)

# 溫度
plt.text(
    0.20, 0.68,
    f"{temperature:.1f} °C\nTemperature",
    ha="center",
    fontsize=18
)

# 濕度
plt.text(
    0.50, 0.68,
    f"{humidity:.0f} %\nHumidity",
    ha="center",
    fontsize=18
)

# 風速
plt.text(
    0.80, 0.68,
    f"{wind_speed:.1f} m/s\nWind Speed",
    ha="center",
    fontsize=18
)

# 觀測時間
plt.text(
    0.5, 0.42,
    f"Observation Time\n{observation_time}",
    ha="center",
    fontsize=14
)

# 資料來源
plt.text(
    0.5, 0.20,
    "Data Source\nCentral Weather Administration Open Data",
    ha="center",
    fontsize=12
)

# 儲存成果圖
plt.savefig(
    "taipei_weather_card.png",
    dpi=150,
    bbox_inches="tight"
)

plt.show()
