# -*- coding: utf-8 -*-
"""「Taiwan_Weather_Analysis_V5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16PdlWjMieSk4VZwwL9ekis_iE2k81szk
"""

import requests

API_KEY = "CWA-17973F66-40B3-4A81-BE7A-2E61598C73BF"

url = "https://opendata.cwa.gov.tw/api/v1/rest/datastore/O-A0001-001"

params = {
    "Authorization": API_KEY,
    "format": "JSON"
}

response = requests.get(url, params=params, verify=False)

print("連線狀態：", response.status_code)

# 將中央氣象署回傳資料轉成 JSON
data = response.json()

# 取得所有氣象站資料
stations = data["records"]["Station"]

print("取得測站數量：", len(stations))

# 尋找臺北、臺中、高雄測站
target_cities = ["臺北", "臺中", "高雄"]

for city in target_cities:
    print("\n==========", city, "==========")

    for station in stations:
        station_name = station["StationName"]

        if city in station_name:
            print(
                "測站名稱：", station_name,
                "｜測站代碼：", station["StationId"]
            )

# ==========================================
# V5：取得臺北、臺中、高雄即時氣象資料
# ==========================================

target_stations = {
    "臺北": "466920",
    "臺中": "467490",
    "高雄": "467441"
}

city_weather = {}

for station in stations:

    station_id = station["StationId"]

    for city, target_id in target_stations.items():

        if station_id == target_id:

            weather = station["WeatherElement"]

            city_weather[city] = {
                "測站": station["StationName"],
                "溫度": weather["AirTemperature"],
                "濕度": weather["RelativeHumidity"],
                "風速": weather["WindSpeed"],
                "觀測時間": station["ObsTime"]["DateTime"]
            }

# 顯示結果
for city, info in city_weather.items():

    print("==========", city, "==========")
    print("測站：", info["測站"])
    print("溫度：", info["溫度"], "°C")
    print("相對濕度：", info["濕度"], "%")
    print("風速：", info["風速"], "m/s")
    print("觀測時間：", info["觀測時間"])
    print()

# ==========================================
# V5：三城市即時溫度比較圖
# ==========================================

import matplotlib.pyplot as plt

cities = ["Taipei", "Taichung", "Kaohsiung"]

temperatures = [
    float(city_weather["臺北"]["溫度"]),
    float(city_weather["臺中"]["溫度"]),
    float(city_weather["高雄"]["溫度"])
]

plt.figure(figsize=(9, 5))

bars = plt.bar(cities, temperatures)

plt.title("Taiwan City Real-Time Temperature Comparison")
plt.xlabel("City")
plt.ylabel("Temperature (°C)")

# 在柱狀圖上顯示數值
for bar, value in zip(bars, temperatures):
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height() + 0.1,
        f"{value:.1f} °C",
        ha="center"
    )

plt.ylim(0, max(temperatures) + 5)
plt.grid(axis="y", alpha=0.3)

plt.tight_layout()

# 儲存圖片
plt.savefig(
    "city_temperature_comparison.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

# ==========================================
# V5：三城市即時相對濕度比較圖
# ==========================================

import matplotlib.pyplot as plt

cities = ["Taipei", "Taichung", "Kaohsiung"]

humidity = [
    float(city_weather["臺北"]["濕度"]),
    float(city_weather["臺中"]["濕度"]),
    float(city_weather["高雄"]["濕度"])
]

plt.figure(figsize=(9, 5))

bars = plt.bar(cities, humidity)

plt.title("Taiwan City Real-Time Humidity Comparison")
plt.xlabel("City")
plt.ylabel("Relative Humidity (%)")

# 在柱子上顯示濕度
for bar, value in zip(bars, humidity):
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height() + 1,
        f"{value:.0f} %",
        ha="center"
    )

plt.ylim(0, 100)
plt.grid(axis="y", alpha=0.3)

plt.tight_layout()

# 儲存圖片
plt.savefig(
    "city_humidity_comparison.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

# ==========================================
# V6：三城市即時氣象自動分析
# ==========================================

# 取得三城市溫度
temperature_data = {
    "臺北": float(city_weather["臺北"]["溫度"]),
    "臺中": float(city_weather["臺中"]["溫度"]),
    "高雄": float(city_weather["高雄"]["溫度"])
}

# 找出最高溫與最低溫城市
highest_temp_city = max(temperature_data, key=temperature_data.get)
lowest_temp_city = min(temperature_data, key=temperature_data.get)

highest_temp = temperature_data[highest_temp_city]
lowest_temp = temperature_data[lowest_temp_city]

# 計算最高與最低溫差
temperature_difference = highest_temp - lowest_temp

print("===== 三城市即時溫度分析 =====")
print(f"最高溫城市：{highest_temp_city} {highest_temp:.1f} °C")
print(f"最低溫城市：{lowest_temp_city} {lowest_temp:.1f} °C")
print(f"最高與最低溫差：{temperature_difference:.1f} °C")

# ==========================================
# V6：三城市濕度與風速自動分析
# ==========================================

# 三城市濕度
humidity_data = {
    "臺北": float(city_weather["臺北"]["濕度"]),
    "臺中": float(city_weather["臺中"]["濕度"]),
    "高雄": float(city_weather["高雄"]["濕度"])
}

# 三城市風速
wind_data = {
    "臺北": float(city_weather["臺北"]["風速"]),
    "臺中": float(city_weather["臺中"]["風速"]),
    "高雄": float(city_weather["高雄"]["風速"])
}

# 找出濕度最高與最低城市
highest_humidity_city = max(humidity_data, key=humidity_data.get)
lowest_humidity_city = min(humidity_data, key=humidity_data.get)

# 找出風速最高與最低城市
highest_wind_city = max(wind_data, key=wind_data.get)
lowest_wind_city = min(wind_data, key=wind_data.get)

print("===== 三城市濕度分析 =====")
print(f"濕度最高城市：{highest_humidity_city} {humidity_data[highest_humidity_city]:.0f} %")
print(f"濕度最低城市：{lowest_humidity_city} {humidity_data[lowest_humidity_city]:.0f} %")

print()

print("===== 三城市風速分析 =====")
print(f"風速最高城市：{highest_wind_city} {wind_data[highest_wind_city]:.1f} m/s")
print(f"風速最低城市：{lowest_wind_city} {wind_data[lowest_wind_city]:.1f} m/s")

# ==========================================
# V6：自動產生氣象分析結論
# ==========================================

print("===== 臺灣三城市即時氣象分析報告 =====")
print()

print(
    f"目前三城市中，{highest_temp_city}氣溫最高，"
    f"為 {highest_temp:.1f} °C；"
    f"{lowest_temp_city}氣溫最低，"
    f"為 {lowest_temp:.1f} °C。"
)

print(
    f"最高溫與最低溫相差 "
    f"{temperature_difference:.1f} °C。"
)

print(
    f"相對濕度方面，以{highest_humidity_city}最高，"
    f"達 {humidity_data[highest_humidity_city]:.0f}%；"
    f"{lowest_humidity_city}最低，"
    f"為 {humidity_data[lowest_humidity_city]:.0f}%。"
)

print(
    f"風速方面，以{highest_wind_city}最高，"
    f"為 {wind_data[highest_wind_city]:.1f} m/s；"
    f"{lowest_wind_city}最低，"
    f"為 {wind_data[lowest_wind_city]:.1f} m/s。"
)

print()
print("以上分析結果由中央氣象署 Open Data 即時資料自動計算產生。")

# ==========================================
# V6：即時氣象智慧分析 Dashboard
# ==========================================

import matplotlib.pyplot as plt

cities_en = ["Taipei", "Taichung", "Kaohsiung"]

temperatures = [
    temperature_data["臺北"],
    temperature_data["臺中"],
    temperature_data["高雄"]
]

humidities = [
    humidity_data["臺北"],
    humidity_data["臺中"],
    humidity_data["高雄"]
]

winds = [
    wind_data["臺北"],
    wind_data["臺中"],
    wind_data["高雄"]
]

fig, ax = plt.subplots(figsize=(12, 7))

x = range(len(cities_en))
width = 0.25

bars1 = ax.bar(
    [i - width for i in x],
    temperatures,
    width,
    label="Temperature (°C)"
)

bars2 = ax.bar(
    x,
    humidities,
    width,
    label="Humidity (%)"
)

bars3 = ax.bar(
    [i + width for i in x],
    winds,
    width,
    label="Wind Speed (m/s)"
)

ax.set_title(
    "Taiwan Real-Time Weather Smart Analysis Dashboard",
    fontsize=18,
    fontweight="bold"
)

ax.set_xticks(list(x))
ax.set_xticklabels(cities_en)
ax.set_ylabel("Observed Value")
ax.legend()
ax.grid(axis="y", alpha=0.3)

# 顯示數值
for bar, value in zip(bars1, temperatures):
    ax.text(
        bar.get_x() + bar.get_width()/2,
        bar.get_height() + 1,
        f"{value:.1f}°C",
        ha="center"
    )

for bar, value in zip(bars2, humidities):
    ax.text(
        bar.get_x() + bar.get_width()/2,
        bar.get_height() + 1,
        f"{value:.0f}%",
        ha="center"
    )

for bar, value in zip(bars3, winds):
    ax.text(
        bar.get_x() + bar.get_width()/2,
        bar.get_height() + 1,
        f"{value:.1f}",
        ha="center"
    )

# 自動分析摘要
analysis_text = (
    f"Highest Temperature: {highest_temp_city} {highest_temp:.1f}°C\n"
    f"Temperature Difference: {temperature_difference:.1f}°C\n"
    f"Highest Humidity: {highest_humidity_city} "
    f"{humidity_data[highest_humidity_city]:.0f}%\n"
    f"Highest Wind Speed: {highest_wind_city} "
    f"{wind_data[highest_wind_city]:.1f} m/s"
)

fig.text(
    0.5,
    0.01,
    analysis_text,
    ha="center",
    fontsize=11
)

plt.tight_layout(rect=[0, 0.14, 1, 1])

plt.savefig(
    "weather_smart_analysis_dashboard.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

# ==================================================
# V7：即時氣象智慧生活建議系統
# ==================================================

print("===== 臺灣三城市智慧生活建議 =====")
print()

for city in ["臺北", "臺中", "高雄"]:

    temp = float(city_weather[city]["溫度"])
    humidity = float(city_weather[city]["濕度"])
    wind = float(city_weather[city]["風速"])

    suggestions = []

    # -------------------------
    # 溫度判斷
    # -------------------------
    if temp >= 35:
        suggestions.append("高溫警示：避免長時間戶外活動，注意補充水分。")
    elif temp >= 30:
        suggestions.append("天氣偏熱：外出建議做好防曬並適時補充水分。")
    elif temp <= 15:
        suggestions.append("氣溫偏低：外出建議增加保暖衣物。")
    else:
        suggestions.append("目前氣溫適中。")

    # -------------------------
    # 濕度判斷
    # -------------------------
    if humidity >= 80:
        suggestions.append("濕度偏高：室內可適度使用除濕設備。")
    elif humidity <= 40:
        suggestions.append("空氣較乾燥：注意補充水分及皮膚保濕。")
    else:
        suggestions.append("目前濕度在一般範圍。")

    # -------------------------
    # 風速判斷
    # -------------------------
    if wind >= 10:
        suggestions.append("風勢較強：戶外活動及騎乘交通工具請注意安全。")
    elif wind >= 5:
        suggestions.append("風速稍強：戶外活動請留意周遭環境。")
    else:
        suggestions.append("目前風速較平穩。")

    # -------------------------
    # 顯示結果
    # -------------------------
    print(f"【{city}】")
    print(f"溫度：{temp:.1f} °C")
    print(f"相對濕度：{humidity:.0f} %")
    print(f"風速：{wind:.1f} m/s")

    print("智慧建議：")

    for suggestion in suggestions:
        print("．" + suggestion)

    print("--------------------------------")

# ==================================================
# V7.2：智慧氣象決策 Dashboard
# ==================================================

import matplotlib.pyplot as plt

cities = ["Taipei", "Taichung", "Kaohsiung"]

temperatures = [
    float(city_weather["臺北"]["溫度"]),
    float(city_weather["臺中"]["溫度"]),
    float(city_weather["高雄"]["溫度"])
]

humidities = [
    float(city_weather["臺北"]["濕度"]),
    float(city_weather["臺中"]["濕度"]),
    float(city_weather["高雄"]["濕度"])
]

winds = [
    float(city_weather["臺北"]["風速"]),
    float(city_weather["臺中"]["風速"]),
    float(city_weather["高雄"]["風速"])
]

# 建立畫布
fig, ax = plt.subplots(figsize=(12, 7))

# 隱藏座標軸
ax.axis("off")

# 標題
ax.text(
    0.5, 0.94,
    "Taiwan Smart Weather Decision Dashboard",
    ha="center",
    va="center",
    fontsize=22,
    fontweight="bold"
)

# 三城市位置
x_positions = [0.18, 0.50, 0.82]

for i, city in enumerate(cities):

    temp = temperatures[i]
    humidity = humidities[i]
    wind = winds[i]

    # 自動產生簡短建議
    advice = []

    if temp >= 30:
        advice.append("Hot - Hydrate")
    else:
        advice.append("Temperature OK")

    if humidity >= 80:
        advice.append("Use Dehumidifier")
    else:
        advice.append("Humidity OK")

    if wind >= 5:
        advice.append("Strong Wind")
    else:
        advice.append("Wind Stable")

    advice_text = "\n".join(advice)

    # 城市名稱
    ax.text(
        x_positions[i], 0.78,
        city,
        ha="center",
        fontsize=18,
        fontweight="bold"
    )

    # 即時資料
    ax.text(
        x_positions[i], 0.60,
        f"Temperature\n{temp:.1f} °C\n\n"
        f"Humidity\n{humidity:.0f} %\n\n"
        f"Wind Speed\n{wind:.1f} m/s",
        ha="center",
        va="center",
        fontsize=14,
        bbox=dict(
            boxstyle="round,pad=0.8",
            alpha=0.15
        )
    )

    # 智慧建議
    ax.text(
        x_positions[i], 0.25,
        advice_text,
        ha="center",
        va="center",
        fontsize=12,
        fontweight="bold"
    )

# 資料來源
ax.text(
    0.5, 0.05,
    "Data Source: Central Weather Administration Open Data API",
    ha="center",
    fontsize=10
)

plt.tight_layout()

# 儲存成果
plt.savefig(
    "smart_weather_decision_dashboard.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

# ==================================================
# V8：互動式智慧氣象查詢系統
# ==================================================

from ipywidgets import Dropdown, Button, Output, VBox
from IPython.display import display

# 城市選單
city_selector = Dropdown(
    options=["臺北", "臺中", "高雄"],
    value="臺北",
    description="選擇城市："
)

# 查詢按鈕
query_button = Button(
    description="查詢即時氣象",
    button_style="info"
)

# 顯示結果區
output = Output()


def smart_weather_advice(temp, humidity, wind):

    advice = []

    # 溫度判斷
    if temp >= 35:
        advice.append("🔴 高溫警示：避免長時間戶外活動並補充水分。")
    elif temp >= 30:
        advice.append("☀️ 天氣偏熱：建議做好防曬並補充水分。")
    elif temp <= 15:
        advice.append("🧥 氣溫偏低：外出請注意保暖。")
    else:
        advice.append("🌤️ 目前氣溫適中。")

    # 濕度判斷
    if humidity >= 80:
        advice.append("💧 濕度偏高：室內可適度使用除濕設備。")
    elif humidity <= 40:
        advice.append("🌵 空氣較乾燥：注意補充水分與保濕。")
    else:
        advice.append("💧 目前濕度在一般範圍。")

    # 風速判斷
    if wind >= 10:
        advice.append("⚠️ 風勢較強：戶外活動請注意安全。")
    elif wind >= 5:
        advice.append("🍃 風速稍強：請留意戶外環境。")
    else:
        advice.append("🍃 目前風速較平穩。")

    return advice


def show_weather(button):

    with output:

        output.clear_output()

        city = city_selector.value

        temp = float(city_weather[city]["溫度"])
        humidity = float(city_weather[city]["濕度"])
        wind = float(city_weather[city]["風速"])

        print("=" * 35)
        print(f"     {city} 即時智慧氣象資訊")
        print("=" * 35)

        print(f"🌡️ 溫度：{temp:.1f} °C")
        print(f"💧 相對濕度：{humidity:.0f} %")
        print(f"🍃 風速：{wind:.1f} m/s")

        print()
        print("【智慧生活建議】")

        advice = smart_weather_advice(
            temp,
            humidity,
            wind
        )

        for item in advice:
            print(item)

        print()
        print("資料來源：中央氣象署 Open Data API")


# 按下按鈕時執行查詢
query_button.on_click(show_weather)

# 顯示互動介面
display(
    VBox([
        city_selector,
        query_button,
        output
    ])
)

# ==========================================
# V5：三城市即時風速比較圖
# ==========================================

import matplotlib.pyplot as plt

cities = ["Taipei", "Taichung", "Kaohsiung"]

wind_speed = [
    float(city_weather["臺北"]["風速"]),
    float(city_weather["臺中"]["風速"]),
    float(city_weather["高雄"]["風速"])
]

plt.figure(figsize=(9, 5))

bars = plt.bar(cities, wind_speed)

plt.title("Taiwan City Real-Time Wind Speed Comparison")
plt.xlabel("City")
plt.ylabel("Wind Speed (m/s)")

# 在柱子上顯示風速
for bar, value in zip(bars, wind_speed):
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height() + 0.05,
        f"{value:.1f} m/s",
        ha="center"
    )

plt.grid(axis="y", alpha=0.3)

plt.tight_layout()

# 儲存圖片
plt.savefig(
    "city_wind_speed_comparison.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

# ==========================================
# V5：Taiwan Real-Time Weather Dashboard
# ==========================================

import matplotlib.pyplot as plt
import numpy as np

cities = ["Taipei", "Taichung", "Kaohsiung"]

temperature = [
    float(city_weather["臺北"]["溫度"]),
    float(city_weather["臺中"]["溫度"]),
    float(city_weather["高雄"]["溫度"])
]

humidity = [
    float(city_weather["臺北"]["濕度"]),
    float(city_weather["臺中"]["濕度"]),
    float(city_weather["高雄"]["濕度"])
]

wind_speed = [
    float(city_weather["臺北"]["風速"]),
    float(city_weather["臺中"]["風速"]),
    float(city_weather["高雄"]["風速"])
]

# 建立位置
x = np.arange(len(cities))
width = 0.25

plt.figure(figsize=(11, 6))

# 三組長條
bars1 = plt.bar(x - width, temperature, width, label="Temperature (°C)")
bars2 = plt.bar(x, humidity, width, label="Humidity (%)")
bars3 = plt.bar(x + width, wind_speed, width, label="Wind Speed (m/s)")

# 標題
plt.title(
    "Taiwan Real-Time Weather Dashboard",
    fontsize=18,
    fontweight="bold"
)

plt.xlabel("City")
plt.ylabel("Observed Value")

plt.xticks(x, cities)

plt.legend()

plt.grid(
    axis="y",
    alpha=0.3
)

# 顯示數值
for bar, value in zip(bars1, temperature):
    plt.text(
        bar.get_x() + bar.get_width()/2,
        bar.get_height() + 1,
        f"{value:.1f}°C",
        ha="center"
    )

for bar, value in zip(bars2, humidity):
    plt.text(
        bar.get_x() + bar.get_width()/2,
        bar.get_height() + 1,
        f"{value:.0f}%",
        ha="center"
    )

for bar, value in zip(bars3, wind_speed):
    plt.text(
        bar.get_x() + bar.get_width()/2,
        bar.get_height() + 1,
        f"{value:.1f}",
        ha="center"
    )

plt.tight_layout()

# 儲存 Dashboard
plt.savefig(
    "taiwan_weather_dashboard.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

# V4.3：取得臺北測站即時氣象資料

taipei_station = None

# 找出臺北測站
for station in stations:
    if station["StationName"] == "臺北":
        taipei_station = station
        break

# 顯示臺北測站資料
if taipei_station:
    print("=== 臺北測站即時氣象資料 ===")
    print("測站名稱：", taipei_station["StationName"])
    print("測站代碼：", taipei_station["StationId"])
    print("觀測時間：", taipei_station["ObsTime"]["DateTime"])

    weather = taipei_station["WeatherElement"]

    print("溫度：", weather["AirTemperature"], "°C")
    print("相對濕度：", weather["RelativeHumidity"], "%")
    print("風速：", weather["WindSpeed"], "m/s")
else:
    print("找不到臺北測站")

# V4.4：臺北即時氣象資料視覺化

import matplotlib.pyplot as plt

# 將中央氣象署 API 回傳的文字轉成數值
temperature = float(weather["AirTemperature"])
humidity = float(weather["RelativeHumidity"])
wind_speed = float(weather["WindSpeed"])

print("=== 臺北即時氣象資料 ===")
print("溫度：", temperature, "°C")
print("相對濕度：", humidity, "%")
print("風速：", wind_speed, "m/s")

# 建立圖表資料
items = [
    "Temperature (°C)",
    "Humidity (%)",
    "Wind Speed (m/s)"
]

values = [
    temperature,
    humidity,
    wind_speed
]

# 建立長條圖
plt.figure(figsize=(9, 5))

bars = plt.bar(items, values)

plt.title("Taipei Real-Time Weather Observation")
plt.ylabel("Observed Value")

# 在每個柱子上方顯示實際數值
for bar, value in zip(bars, values):
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height() + 1,
        f"{value:g}",
        ha="center"
    )

plt.tight_layout()

# 儲存圖片
plt.savefig(
    "taipei_realtime_weather.png",
    dpi=150,
    bbox_inches="tight"
)

plt.show()

# V4.5：臺北即時天氣資訊卡

import matplotlib.pyplot as plt

# 使用 V4.3 已取得的真實氣象資料
temperature = float(weather["AirTemperature"])
humidity = float(weather["RelativeHumidity"])
wind_speed = float(weather["WindSpeed"])

# 取得觀測時間
observation_time = taipei_station["ObsTime"]["DateTime"]

# 建立資訊卡
fig = plt.figure(figsize=(9, 7))

# 關閉座標軸
plt.axis("off")

# 標題
plt.text(
    0.5, 0.92,
    "Taipei Real-Time Weather",
    ha="center",
    fontsize=22,
    fontweight="bold"
)

# 溫度
plt.text(
    0.20, 0.68,
    f"{temperature:.1f} °C\nTemperature",
    ha="center",
    fontsize=18
)

# 濕度
plt.text(
    0.50, 0.68,
    f"{humidity:.0f} %\nHumidity",
    ha="center",
    fontsize=18
)

# 風速
plt.text(
    0.80, 0.68,
    f"{wind_speed:.1f} m/s\nWind Speed",
    ha="center",
    fontsize=18
)

# 觀測時間
plt.text(
    0.5, 0.42,
    f"Observation Time\n{observation_time}",
    ha="center",
    fontsize=14
)

# 資料來源
plt.text(
    0.5, 0.20,
    "Data Source\nCentral Weather Administration Open Data",
    ha="center",
    fontsize=12
)

# 儲存成果圖
plt.savefig(
    "taipei_weather_card.png",
    dpi=150,
    bbox_inches="tight"
)

plt.show()
